### ISSUE TITLE
hashlib losing ripemd160 support

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/bitcoinX#12]
Apparently, hashlib in the standard library relies on openssl and openssl is removing ripemd160 support. ElectrumSV uses it through bitcoinx. Thoughts?

https://github.com/electrumsv/electrumsv/issues/888

**Comment by kyuupichan** [comment]
If this really is disappearing from Python's API, then we should copy-and-paste the code and add it to your electrumsv-libsecp256k1 IMO.  I will then get bitcoinX to use that like it does for the other crypto functions.

**Comment by rt121212121** [comment]
When you say "we" is there any chance you mean you? :-)

**Comment by rt121212121** [comment]
Another option is to drop pyaes support and accept pycryptodomex as a proper dependency. From ESV's perspective the big gain for fast aes was when we had json dumps encrypted as save files. I believe pycryptodomex has ripemd160 as well.

https://pycryptodome.readthedocs.io/en/latest/src/hash/ripemd160.html

However I am not adverse to the expansion of libsecp256k1 as an option although I would prefer you do it rather than me :-)

**Comment by rt121212121** [comment]
A C option for libsecp256k1 integration.

https://github.com/Legrandin/pycryptodome/blob/5dace638b70ac35bb5d9b565f3e75f7869c9d851/src/RIPEMD160.c

**Comment by rt121212121** [comment]
There's also the Bitcoin C++ implementation.

**Comment by kyuupichan** [comment]
The code was updated to use pycryptodomex
