### ISSUE TITLE
PublicKey.from_hex/from_bytes need coin argument

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/bitcoinX#8]
In ESV, code passes in the current coin to relevant calls. Where it does `PublicKey.from_hex` (which calls `from_bytes`) it has no ability to pass in the coin, so has to manually set it for now with `public_key._coin = Net.COIN`.

**Comment by kyuupichan** [comment]
I have tried, where possible, to remove the two things that are not really properties of the public keys: namely whether compressed, and the coin.  These are private members only to remember creation context where it would be awkward not to.  

Instead I preferred to pass the coin in the few function calls it was needed, such as converting to a base-58 address.  Is that not possible in ESV?  Can you explain your use-case / point me at it?

**Comment by rt121212121** [comment]
I thought the code path to display did not involve any way to specify a coin, but I was wrong. I'll close the issue.

**Comment by kyuupichan** [comment]
OK that's great.  If something is needed happy to discuss and find a way.  Thinking about this has made me think the optional value to the constructors should not be something specific like uncompressed or coin, but a single "presentation" object (which would hold both of those things, but be logically expansible too in future).
